spring.application.name=memories-api
server.port=9090
server.tomcat.connection-timeout=60000

spring.security.user.name=admin
spring.security.user.password=admin

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name= org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# Enable logging for SQL queries
logging.level.org.hibernate.SQL=${SQL_LOGGING_LEVEL:DEBUG}
logging.level.org.hibernate.type.descriptor.sql=${SQL_TYPE_DESCRIPTOR:TRACE}
