name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Use GitHub's runner
    container: cimg/openjdk:21.0.5-node  # Use OpenJDK 21 with Node.js

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker environment (fix permissions)
        run: |
          # Ensure the docker group exists
          sudo groupadd docker || true
          # Add the current user to the docker group
          sudo usermod -aG docker $USER
          # Restart Docker to apply changes
          sudo service docker restart
          # Verify Docker group membership (optional)
          id -nG

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract Git Commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            sopratutto/memories-api:latest
            sopratutto/memories-api:${{ env.sha_short }}

      - name: Verify Image on Docker Hub
        run: docker pull sopratutto/memories-api:latest
